In [1]:
import pandas as pd

nhanes = pd.read_csv(
    "../../../examples/nhanes-equity/data/nhanes_equity_v6.csv"
)

nhanes.head()

/tmp/ipykernel_19441/3400587445.py:3: DtypeWarning: Columns (0: Marital, 1: MaritalClean) have mixed types. Specify dtype option on import or set low_memory=False.
  nhanes = pd.read_csv(

,Cycle,BMI,Weight,Height,Waist,WeightMEC,Strata,PSU,Gender,Race,Education,Marital,Age,PIR,EducationClean,MaritalClean,IncomeGroup,WHtR
0,1999-2000,14.90,12.5,91.6,45.7,10982.898896,5,1,Female,Non-Hispanic Black,NaN,NaN,2,0.86,NaN,NaN,Low Income (<1.3),0.498908
1,1999-2000,24.90,75.4,174.0,98.0,28325.384898,1,3,Male,Non-Hispanic White,College Grad,NaN,77,5.00,College Grad,NaN,High Income (>3.5),0.563218
2,1999-2000,17.63,32.9,136.6,64.7,46192.256945,7,2,Female,Non-Hispanic White,NaN,NaN,10,1.47,NaN,NaN,Middle Income,0.473646
3,1999-2000,NaN,13.3,NaN,NaN,10251.260020,2,1,Male,Non-Hispanic Black,NaN,NaN,1,0.57,NaN,NaN,Low Income (<1.3),NaN
4,1999-2000,29.10,92.5,178.3,99.9,99445.065735,8,2,Male,Non-Hispanic White,College Grad,Married/Partner,49,5.00,College Grad,Married/Partner,High Income (>3.5),0.560292

In [2]:
import sys

sys.path.insert(0, "assignments/assignment04-polyglot/submission")

from helpers import summarise_bmi

# Calculate dataset dimensions
raw_row_count = len(nhanes)
raw_column_count = len(nhanes.columns)

# Remove rows with missing values
filtered = nhanes.dropna(
    subset=["BMI", "IncomeGroup", "Gender"]
)

# Calculate BMI summary using our helper
bmi_summary = summarise_bmi(nhanes)

# Display parity metrics
print("Raw rows:", raw_row_count)
print("Raw columns:", raw_column_count)
print("Filtered rows:", len(filtered))
print("Number of groups:", len(bmi_summary))

# Display rounded summary
display(bmi_summary.round(2))

Raw rows: 105626
Raw columns: 18
Filtered rows: 87647
Number of groups: 6

          IncomeGroup  Gender      n  mean_bmi  median_bmi  sd_bmi
0  High Income (>3.5)  Female  11743     25.74       24.60    7.51
1  High Income (>3.5)    Male  12095     26.11       26.00    6.81
2   Low Income (<1.3)  Female  16548     25.95       24.66    8.65
3   Low Income (<1.3)    Male  14847     24.05       23.30    7.17
4       Middle Income  Female  16432     26.39       25.30    8.20
5       Middle Income    Male  15982     25.52       25.10    7.22

In [3]:
print(
    bmi_summary[
        ["IncomeGroup", "Gender", "mean_bmi", "median_bmi", "sd_bmi"]
    ].round(2).to_string(index=False)
)

       IncomeGroup Gender  mean_bmi  median_bmi  sd_bmi
High Income (>3.5) Female     25.74       24.60    7.51
High Income (>3.5)   Male     26.11       26.00    6.81
 Low Income (<1.3) Female     25.95       24.66    8.65
 Low Income (<1.3)   Male     24.05       23.30    7.17
     Middle Income Female     26.39       25.30    8.20
     Middle Income   Male     25.52       25.10    7.22